### ISSUE TITLE
Git repository contains files that should be ignored

### ISSUE THREAD

**Issue by terrehbyte** [cj9806/CodeDesignAndDataStructures#1]
Looks like you're having some trouble due to the presence of debugging and generated Visual Studio files, as seen in 632fe44.

I'd recommend taking the following steps:

## Remove any extra files and folders

The following paths are problematic and should be removed from the repo.

- .vs/
- Debug/
- x64/
- CodeDesignAndDataStructures/
  - .vs/
  - Debug/
  - x64/
  - *.user
- DynamicArrays/ (same as above -- these are both project folders)
 
They're important while you're working, but they don't belong on Git.

## Update your .gitignore

Copy the contents of the [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) into your .gitignore file.

## Commit and push
👆

Let me know if you need help w/ any of this!

**Comment by cj9806** [comment]
Good to know, was not sure why I was having issues pushing to git, the gitignore was updated on push [83b84ab](https://github.com/cj9806/CodeDesignAndDataStructures/commit/83b84ab72bf71a818bbeb47b577fac9ef04584c2)
